{% set name = "blueskyapi" %}
{% set version = "0.2.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d955dc016b25f6b6bca42410b0c16fa77004ab7fbfef1b85d5eaf1710afd6ed2

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry-core >=1.0.0
  run:
    - pandas >=1.1,<2.0
    - python >={{ python_min }}
    - requests >=2.0,<3.0

test:
  imports:
    - blueskyapi
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://blueskyapi.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Client for blueskyapi.io
  doc_url: https://blueskyapi.readthedocs.io/en/latest/
  dev_url: https://github.com/bluesky-api/python-client

extra:
  recipe-maintainers:
    - maxhollmann
